### ISSUE TITLE
Checking out personal repo still appears to be broken

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/git-fleximod#24]
First let me say, a couple of things I like that you've changed:
- The listing is much more succinct and useful
- Rerunning git-fleximod with no changes does not say it is checking out anything
- shallow checkouts are occurring (RRTMGP is MUCH smaller)!

-----

That said, the personal repo checkout still does not appear to be working.

In .gitmodules, I changed:

```
[submodule "atmos_phys"]
path = src/atmos_phys
url = https://github.com/ESCOMP/cacraigucar
fxtag = 3976780
fxurl = https://github.com/ESCOMP/atmospheric_physics
fxrequired = AlwaysRequired

```
I see in the listing:
```
Successfully checked out           atmos_phys
          atmos_phys updated to 3976780
```

When I cd to src/atmos_phys and do a git log, I see the original checkout:

```
commit bdbf4e08581f818ae12fb459fb6e017a9458c8fc (HEAD, tag: atmos_phys0_02_000)
Merge: 5dd0c55 859e059
Author: cacraigucar <cacraig@ucar.edu>
Date:   Fri Jan 19 14:24:40 2024 -0700
```

A followon is that setting fxtag=ZZZZZZZZZZ

gives the following output:
```
Successfully checked out           atmos_phys
          atmos_phys updated to ZZZZZZZZZZ
```

**Comment by cacraigucar** [comment]
OK- Halfway user error, but still a bug.

I changed the wrong URL.  Since fxtag is what we change, fxurl is the one I naturally gravite to changing.  Please change the name of fxurl to something more descriptive so that folks don't accidentally change it.  (And I'm a user in the know, that put this aside for a week and got it wrong when I came back!)

Second thing with this issue is that specifying an invalid tag, still does say:
```
Successfully checked out           atmos_phys
          atmos_phys updated to ZZZZZZZZZZZZZZZZZZZZ
```
It reverts back to the default checkout.

**Comment by jedwards4b** [comment]
Fixed by explainM PR.
