### ISSUE TITLE
git-fleximod requires an ssh password for cprnc

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/git-fleximod#25]
I believe you had said that git-fleximod would address this problem.  I'm unable to test this as it remembers my password being provided from ages ago, so I don't know if you've recently fixed this.

@jtruesdal reported that he needed to type in his password for ssh.  Any idea on why this might need to be done?

```
Successfully checked out parallelio /project/amp/jet/collections/CAM_flexi/libraries/parallelio
          parallelio up to date.
Recursively checking out submodules of cime /project/amp/jet/collections/CAM_flexi/cime https://github.com/jedwards4b/cime
Enter passphrase for key '/home/jet/.ssh/id_ed25519': 
e    CIME/non_py/cprnc not checked out, out of sync at tag None, expected tag is v1.0.6
Successfully checked out CIME/non_py/cprnc /project/amp/jet/collections/CAM_flexi/cime/CIME/non_py/cprnc
```

**Comment by jedwards4b** [comment]
You can test by doing mv ~/.ssh ~/save.ssh first then running tests then putting back the .ssh directory.

I did find and fix a case where this wasn't working.
