### ISSUE TITLE
Change name for tool wrapper to manage_externals

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/git-fleximod#33]
@peverwhee had made the request that instead of the wrapper tool be called manage_externals for consistency sake.  It sounded like folks in the CSEG meeting thought this was a good idea.

Could this reside in the main checkout directory instead of in bin?

**Comment by jedwards4b** [comment]
I thought that idea was rejected in the end.  I don't recall why at the moment, but if you want that in your cam repo I guess you can add it.   The code that is in bin is very short:
```
#!/usr/bin/env python3
import sys
import os
sys.path.insert(0,os.path.abspath(os.path.join(os.path.dirname(__file__),"..",".lib","git-fleximod")))
from git_fleximod.git_fleximod import main

if __name__ == '__main__':
    sys.exit(main())

```
You can move it to the top level if you like but be sure and correct the path by removing ".." if you do.

**Comment by cacraigucar** [comment]
No, we will adhere to the rest of CESM.

**Comment by cacraigucar** [comment]
I found this in the CSEG notes - a variation on what we both remembered as the final outcome.

- Courtney: can we have a ./manage_externals/checkout_externals script that runs git-fleximod?
    - Jim’s suggestion is to have it just give you the command to use now
    - Others like that

So I guess this issue should become:
 - Create manage_externals/checkout_externals script which returns the command to use now and perhaps links to the appropriate documentation

**Comment by ekluzek** [comment]
@cacraigucar in CTSM we created such a script here:

https://github.com/ESCOMP/CTSM/blob/master/manage_externals/checkout_externals

It's a simple bash script.

**Comment by jedwards4b** [comment]
I'm not going to do this - if you want to do this in your component repositories go ahead.

**Comment by cacraigucar** [comment]
FYI - CAM has the following in our README.md file:

```
To checkout externals:
    bin/git-fleximod update

The externals are stored in:
    .gitmodules

.gitmodules can be modified.  Then run "bin/git-fleximod update" to get the updated externals

Details about git-fleximod and the variables in the .gitmodules file can be found at:   .lib/git-fleximod/README.md
```

Our script for manage_externals/checkout_externals is:

```
echo "Error:  manage_externals/checkout_externals is no longer supported"
echo "        It has been replaced by bin/git-fleximod"
echo "        Please refer to the README.md file in the home directory of a CAM checkout for more information"
```
