### ISSUE TITLE
Add notes on how to update the git fleximod subtree in a repository

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/git-fleximod#42]
Since, I'm used to updating manage_externals, I was able to update the subtree for git-fleximod. But, I think we should have some documentation somewhere on how to do that. Possibly there already is I just didn't find it.

**Comment by jedwards4b** [comment]
It's here, although git-fleximod is not specifically mentioned. 
https://github.com/ESMCI/cime/wiki/CIME-Git-Workflow

**Comment by ekluzek** [comment]
OK, thanks for that. That gives how to handle git subtrees beneath CIME, but git-fleximod isn't under CIME. So I think there should be instructions on how to handle it for a model separate from CIME.

**Comment by jedwards4b** [comment]
manage_externals was included as a gitsubtree - where are those instructions?

**Comment by ekluzek** [comment]
https://github.com/ESMCI/manage_externals/wiki#including-manage_externals-in-other-repositories

**Comment by dabail10** [comment]
I have a similar question. I am getting the following message. It seems like the e is an error message, but it simply does a recursive submodule update here. Since icepack is a submodule of CICE, should I add fxtag to the .gitmodules under CICE?

```
Recursively checking out submodules of cice

e                  src has no fxtag defined in .gitmodules
Recursively checking out submodules of src

e              icepack has no fxtag defined in .gitmodules
                cice up to date.

```

**Comment by jedwards4b** [comment]
@dabail10 actually your question has nothing to do with this issue.   If you don't have fxtag defined for a submodule, git-fleximod will still work but it warns you that there is no fxtag defined - you don't need to define it but you can if you want.

**Comment by dabail10** [comment]
I realize it wasn't related, but didn't feel it was worth a separate issue.

**Comment by jedwards4b** [comment]
wiki added
