### ISSUE TITLE
git-fleximod --help doesnt work

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/git-fleximod#5]
We need to build a manpage for this option and the 
equivalent `git help fleximod` to work.

**Comment by jedwards4b** [comment]
making --help work with git is not trivial... git receives the --help flag and there is no way to override that behavior for the subcommand to receive that --help...
[stackoverflow](https://stackoverflow.com/questions/60323269/git-subcommand-with-help-arg-not-working)
[git-help](https://git-scm.com/docs/git-help#_configuration_variables )

**Comment by gold2718** [comment]
Maybe this is another sign that this tool is not really a git tool.
Instead of spending time trying to force it into the git framework, why not just have it be a regular Python script (the name manage_externals might be free soon).

**Comment by jedwards4b** [comment]
@gold2718 I really appreciate your skill and knowledge as a software engineer.  I wish I found your comments more helpful instead of destructive.  [Here is another article ](https://opensource.com/article/22/4/customize-git-subcommands)explaining that, yes, my tool really is a git tool.
