### ISSUE TITLE
Failed to checkout CIME/non_py/cprnc

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/git-fleximod#52]
See https://github.com/ESCOMP/CAM/pull/1075#issuecomment-2212309379

**Comment by jedwards4b** [comment]
@nusbaume Can you tell me what system you tried this on and can you try it again on derecho or izumi?

**Comment by nusbaume** [comment]
Hi @jedwards4b , I just tried it on Derecho, Izumi, and my local machine and all three came up with the same error.  If you need any additional info please let me know.

**Comment by jedwards4b** [comment]
Yes @nusbaume - can you point me to the source directory on either of those systems please.

**Comment by nusbaume** [comment]
@jedwards4b sure, you can find my CAM source directory with the failed checkout on Derecho here:

`/glade/derecho/scratch/nusbaume/jedwards_CAM`

Please let me know if you run into any permissions issues or anything.  Thanks!

**Comment by jedwards4b** [comment]
Fixed in v0.8.1
