### ISSUE TITLE
Hang in Submodule._add_remote()

### ISSUE THREAD

**Issue by samsrabin** [ESMCI/git-fleximod#56]
Should line 173 have `newremote` instead of `"newremote"`? I was getting a hang here until I made that change.

https://github.com/ESMCI/git-fleximod/blob/75a03373577f5ed19a00d2c387ca36bff1172d76/git_fleximod/submodule.py#L165-L175

**Comment by jedwards4b** [comment]
@samsrabin Yes, thank you!
