### ISSUE TITLE
git-fleximod is not updating when using hashes and tags

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/git-fleximod#61]
This issue is that git-fleximod needs to trap and error out if a tag/hash does not exist in the repository specified.

-------------

Old details to provide context on the discussion below:

I am getting the following failing test:  https://github.com/ESCOMP/CAM/actions/runs/10411719057/job/28836175227?pr=1127

My workflow was:
Working on my personal branch of atmos_phys, I specified my fork and a hash (4f0766) in a clone
After testing was done, I committed and tagged my atmos_phys changes (with additional mods)
I then updated the .gitmodules in my clone to point to the ESCOMP/atmospheric_physics and tag atmos_phys0_04_001 and ran bin/git-fleximod update
git-fleximod reported "atmos_phys updated to atmos_phys0_04_001", but in reality it did not update

I did not get the updated commit which is seen by the failing test when I opened the PR.

My clone is on izumi:  /home/cacraig/cam_cleanup3a

**Comment by jedwards4b** [comment]
In .gitmodules you have: fxtag =  atmos_phys0_04_001
but the tag you created is atmos_phys_0_04_001

So the real error here is that it didn't clearly show you your error.  I'll work on that.

**Comment by jedwards4b** [comment]
@cacraigucar I think that you should have updates the issue when you corrected the problem.

**Comment by cacraigucar** [comment]
@jedwards4b - Thanks for finding the issue with the tag name.  I fixed that name and git-fleximod checked out the correct information.  

I am pretty sure one of the myriad of tests that I did early on with git-fleximod was providing a tag that did not exist and the git-fleximod caught it.  So perhaps this check went away in subsequent versions?  It would be good to have it trap tags/hashes that do not exist and error out.  

I will leave this issue open to track that and I have updated the description appropriately.

**Comment by jedwards4b** [comment]
@cacraigucar there are two interfaces to git provided.  One is using GitPython and the other is through system calls to git.  The python module works fine and reports error:
```
Cmd('git') failed due to: exit code(128)
  cmdline: git fetch origin refs/tags/atmos_phys0_04_001does_not_exist:refs/tags/atmos_phys0_04_001does_not_exist
  stderr: 'fatal: couldn't find remote ref refs/tags/atmos_phys0_04_001does_not_exist'

```
But the system interface was failing to report an error for this case.
I have corrected the problem to now report
```
git_fleximod.git_fleximod - ERROR - Command ['git', '-C', '/home/jedwards/cam7/src/atmos_phys', 'fetch', 'origin', 'refs/tags/atmos_phys0_04_001_does_not_exist:refs/tags/atmos_phys0_04_001_does_not_exist'] returned an unknown error
```
I recommend that you consider installing the GitPython module for improved error checking.
