### ISSUE TITLE
git-fleximod finds unrelated parent-level .gitmodules file

### ISSUE THREAD

**Issue by peverwhee** [ESMCI/git-fleximod#65]
Though I understand the reason for git-fleximod to find the highest-level .gitmodules file in the directory structure, it would be nice if it would stop searching when outside of the git tree. I ran into the following scenario (which is admittedly a problem of my own doing!):

1. I had a checkout of CAM in `/home/courtneyp/Projects/CAM` on izumi
2. I had a temporary `.gitmodules` file from another project in the parent directory `/home/courtneyp/Projects`
3. I ran `bin/git-fleximod update` in the `/home/courtneyp/Projects/CAM` directory
4. git-fleximod picked up and parsed `/home/courtneyp/Projects/.gitmodules` and I was baffled for some time as to why it was grabbing the wrong externals. (I discovered my error by running git-fleximod with the `--verbose` flag and the "root_dir" was the parent directory - so thanks for the verbose option!)

If this is an overly complicated problem to fix, I'd suggest logging the root directory or full path to the `.gitmodules` file by default (not just in verbose mode) when running `git-fleximod`.

**Comment by jedwards4b** [comment]
Let me see if I can figure out a different way to determine the top of the git tree.

**Comment by jedwards4b** [comment]
Fixed by #66
